version: '3.9'

networks:
  postgres:

services:
  postgres:
    image: postgres
    env_file: ./.env
    ports:
      - "5432"
    networks:
      - postgres

  backend:
    build:
      context: backend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 8080 -b '0.0.0.0'"

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
      # - "24678:24678"
    volumes:
      - ./frontend:/usr/src/app
